#!/bin/bash
# sbbscvs2git - v0.3 - Robert James Clay


PRJDIR=/opt/sbbscvs2git

cd $PRJDIR/repo/fromcvs

LOGDIR=$PRJDIR/logs/fromcvs

#
CVSROOT=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs cvs login"

CVSREPO=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs"

for MODULE in src-sbbs3 run-sbbs3 ctrl docs exec include install lib src text web xtrn
do

  GITREPO=$PRJDIR/repo/fromcvs/$MODULE 

  echo `date` > $LOGDIR/$MODULE-import.start

  git-cvsimport -a -p1 -C $GITREPO -d $CVSREPO $MODULE 1>$LOGDIR/$MODULE-import.log 2>$LOGDIR/$MODULE-error.log

  echo `date` > $LOGDIR/$MODULE-import.stop

done
