#!/bin/bash
# sbbscvs2git - v0.3 - Robert James Clay


PRJDIR=/opt/sbbscvs2git

cd $PRJDIR/repo

#
CVSROOT=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs cvs login"

CVSREPO=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs"

for MODULE in ctrl docs exec include install lib node1 node2 node3 node4 src text web xtrn
do

  GITREPO=$PRJDIR/repo/sbbs/$MODULE 

  echo `date` > $PRJDIR/log/$MODULE-import.start

  git-cvsimport -a -p1 -C $GITREPO -d $CVSREPO $MODULE 1>$PRJDIR/log/$MODULE-import.log 2>$PRJDIR/log/$MODULE-error.log

  echo `date` > $PRJDIR/log/$MODULE-import.stop

done
