#!/bin/sh
# sync2git - v0.2 - Robert James Clay


PRJDIR=/opt/sbbscvsgit

cd $PRJDIR/repo

#
CVSROOT=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs cvs login"

CVSREPO=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs"

##  Done
#MODULE=ctrl
#MODULE=docs

MODULE=exec
#MODULE=include
#MODULE=install
#MODULE=lib

#MODULE=node1
#MODULE=node2
#MODULE=node3
#MODULE=node4
#MODULE=src

#MODULE=text
#MODULE=web
#MODULE=xtrn

##  Done


GITREPO=$PRJDIR/repo/sbbs/$MODULE 

echo `date` > $PRJDIR/log/$MODULE-import.start

git-cvsimport -a -p1 -v -C $GITREPO -d $CVSREPO $MODULE 1>$PRJDIR/log/$MODULE-import.log 2>$PRJDIR/log/$MODULE-error.log

echo `date` > $PRJDIR/log/$MODULE-import.stop


