#!/bin/bash
# scripts/create-orig-source for sbbscvs Debian package
# For Synchronet BBS from the current CVS archives. 
#
# Copyright 2011 Robert James Clay <jame@rocasa.us>, GPL2+
#
#Procedure for createing a source archive
#=========================================

# If the working directory path is not passed on the command line,
# then use the current directory.
if [ -z "$1" ]; then
    # Use the current directory as the working directory 
    WORKDIR=`pwd`
else
    # Set working directory to that passed on the command line
    WORKDIR=$1
    # If working directory is not present, create it & change to it
    if [ ! -d $WORKDIR ]; then
	mkdir $WORKDIR
	cd $WORKDIR
    fi
fi

# The format of the version string for the acrhive is YYMMDD, where YY is the
# last two digits of the year, MM is the month number, & DD is the day number.
# The date of the source code archive is noted in the FILE_ID.DIZ file in the
# sbbs_src.tgz source archive.  For now, creating it from todays date.
YYMMDD=`date +%y%m%d`

# Set working source directory
SRCDIR=$WORKDIR/sbbscvs-$YYMMDD

 # Create source directory named in the format sbbscvs-YYMMDD if not already present
if [ ! -d $SRCDIR ]; then
    mkdir $SRCDIR
fi

# If do not already have it in the working directory;  download the file 
# sbbs_src.tgz from ftp://ftp.synchro.net.
if [ ! -e "$WORKDIR/sbbs_src.tgz" ]; then
    wget ftp://ftp.synchro.net/sbbs_src.tgz
fi

# If do not already have it in the working directory;  download the file 
# sbbs_run.tgz from ftp://ftp.synchro.net. (Does not change as often.)
if [ ! -e "$WORKDIR/sbbs_run.tgz" ]; then
    wget ftp://ftp.synchro.net/sbbs_run.tgz
fi

# Extract contents of upstream source archives to source working directory.
cd $SRCDIR
tar -xzvf $WORKDIR/sbbs_run.tgz --exclude=CVS
tar -xzvf $WORKDIR/sbbs_src.tgz --exclude=CVS

#    Make adjustments/changes to source files as neccesary, prior to creating 
#    the new source archive.
#
# Correct the file permissions on the file ircd.conf
chmod 644 $SRCDIR/ctrl/ircd.conf
# Correct the file permissions on the file sync_pbgj1_grey_bg.gif
chmod 644 $SRCDIR/web/root/images/default/sync_pbgj1_grey_bg.gif 
# Delete web/root/images/nightshade/Thumbs.db (Unneeded and it causes a Lintian warning.)
rm -f $SRCDIR/web/root/images/nightshade/Thumbs.db

# Create the source archive from the working source directory.
cd $WORKDIR
tar cfz sbbscvs_$YYMMDD.orig.tar.gz sbbscvs-$YYMMDD/ && rm -fr $WORKDIR/sbbscvs-$YYMMDD
