#!/bin/bash
# fromcvs2git - v0.1 - Robert James Clay
# First stage script, importing Synchronet CVS repository to a set of GIT
# repositories, needed because there is no single base directory available
# via CVS.
#
# Copyright 2011 Robert James Clay <jame@rocasa.us>, GPL2+
#

# Set to the directory where the git executables are located.
LIBDIR=/usr/lib/git-core

PRJDIR=/opt/sbbscvs2git

cd $PRJDIR/scm/fromcvs

LOGDIR=$PRJDIR/logs/fromcvs

#
CVSROOT=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs cvs login"

CVSREPO=":pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs"

for MODULE in ctrl docs exec include install lib src text web xtrn
do

  GITREPO=$PRJDIR/scm/fromcvs/$MODULE 

  echo `date` > $LOGDIR/$MODULE-import.start

  $LIBDIR/git-cvsimport -a -p1 -o $MODULE -C $GITREPO -d $CVSREPO $MODULE 1>$LOGDIR/$MODULE-import.log 2>$LOGDIR/$MODULE-error.log

  echo `date` > $LOGDIR/$MODULE-import.stop

done
